- hosts: g_nfs_client
  tasks:
    - name: "Stop nfs client"
      systemd:
        name: "{{ item }}"
        state: stopped
      with_items:
        - "nfs-mount"
        - "rpcbind"
      ignore_errors: true


    - name: "Remove nfs rpm"
      yum:
        name: "{{ item }}"
        state: absent
      with_items:
        - rpcbind
        - nfs-utils
      ignore_errors: true


    - name: "Remove nfs client file"
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "/etc/systemd/system/nfs-mount.service"
        - "{{ nfs_client_sysnc_path }}"
        - "{{ nfs_client_asysnc_path }}"
      ignore_errors: true

